SELECT * FROM station_types;
SELECT * FROM station_on_route;
SELECT * FROM routes;
SELECT * FROM trains;
SELECT * FROM train_places;
SELECT * FROM place_types;
SELECT * FROM stations;
SELECT * FROM roles;
SELECT * FROM users;